name: Generate Analysis Report

on:
  schedule:
    - cron: '5 3 * * *'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # T채m채 on t채rke채!
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install pandas
      
      - name: Run analysis script
        run: python analyze_data.py
      
      # Artifact tallennus (valinnainen)
      - name: Upload analysis report
        uses: actions/upload-artifact@v4
        with:
          name: analysis-report
          path: AnalyysiRaportti.md
      
      # Muutosten tallentaminen repositorioon
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add AnalyysiRaportti.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update analysis report [automated]"
          git push
