name: Päivitä yleisömäärät

on:
  schedule:
    - cron: '0 20 * * *'  # Päivittäin klo 20:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Asenna järjestelmäriippuvuudet
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver chromium-browser

      - name: Asenna Python-riippuvuudet
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager requests beautifulsoup4

      - name: Alusta tarvittavat tiedostot
        run: |
          if [ ! -f last_audience_id.txt ]; then
            echo "3748451" > last_audience_id.txt
            git add last_audience_id.txt || echo "Tiedoston lisäys epäonnistui"
            git commit -m "Alustava last_audience_id.txt" || echo "Ei committia"
          fi
          mkdir -p audience_cache || true

      - name: Suorita audience scraper
        run: |
          python audience_scraper.py

      - name: Kerää debug-artifaktit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: audience-debug
          path: |
            audience_cache/*.html
            audience_scraper.log

      - name: Päivitä repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add audience_data.json || echo "Ei muutoksia audience_data.json"
          git add last_audience_id.txt || echo "Ei muutoksia last_audience_id.txt"
          git commit -m "Automaattinen yleisödatan päivitys: $(date +'%Y-%m-%d %H:%M %Z')" || echo "Ei commitoitavia muutoksia"
          git pull --rebase
          git push origin HEAD:${{ github.ref }} || echo "Push epäonnistui"

      - name: Näytä lopputulos
        run: |
          echo "Viimeisin ID: $(cat last_audience_id.txt)"
          echo "Data-tiedoston koko: $(ls -lh audience_data.json)"
