name: Päivitä yleisömäärät

on:
  schedule:
    - cron: '0 20 * * *'  # Päivittäin klo 20:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Tarvitaan täysi historiahaku

      - name: Asenna riippuvuudet
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver chromium-browser
          pip install selenium webdriver-manager requests beautifulsoup4

      - name: Tarkista ja alusta last_audience_id.txt
        run: |
          if [ ! -f last_audience_id.txt ]; then
            echo "3748451" > last_audience_id.txt
            git add last_audience_id.txt
            git commit -m "Alustava last_audience_id.txt" || echo "Ei muutoksia"
          fi

      - name: Suorita skripti
        run: python audience_scraper.py

      - name: Päivitä repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add audience_data.json last_audience_id.txt
          git commit -m "Automaattinen päivitys: $(date +'%Y-%m-%d %H:%M')" || echo "Ei muutoksia"
          git push || echo "Push ei onnistunut"
