name: Päivitä veikkausraportti

on:
  schedule:
    - cron: '0 20 * * *'  # Päivittäin klo 20:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout-koodi
        uses: actions/checkout@v4

      - name: Asenna Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Asenna järjestelmäriippuvuudet
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver chromium-browser

      - name: Asenna Python-kirjastot
        run: |
          pip install selenium webdriver-manager requests beautifulsoup4

      - name: Suorita fetch_and_calculate.py
        run: |
          python fetch_and_calculate.py

      - name: Commit ja push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Veikkaustilanne.md
          git commit -m "Automaattinen päivitys: $(date +'%Y-%m-%d %H:%M')"
          git push
