name: Update Football Statistics

on:
  schedule:
    # Runs at 01:00 UTC every day
    - cron: '0 1 * * *'
  workflow_dispatch:
    # Allows manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run the data fetcher script
        run: python fetch_and_calculate.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add Veikkaustilanne.md
          git diff --staged --quiet || git commit -m "Update statistics: $(date +%Y-%m-%d)"
          git push
