name: Päivitä veikkausraportti

on:
  schedule:
    - cron: '50 */3 * * *'  # Ajoitus hieman muutettu
  workflow_dispatch:

jobs:
  update_veikkaus: 
    runs-on: ubuntu-latest
    timeout-minutes: 25 # Hieman enemmän aikaa, jos haku kestää

    steps:
      - name: Checkout-koodi
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Asenna Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      
      - name: Asenna Python-kirjastot
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager requests beautifulsoup4 pathlib # Lisätty pathlib

      - name: Suorita fetch_and_calculate.py
        run: |
          python fetch_and_calculate.py

      - name: Commit ja push Veikkaustilanne.md
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Lisää vain Veikkaustilanne.md ja sen lokitiedosto sekä cache-kansion sisältö
          # Varmista, että nämä polut ovat oikein ja vastaavat fetch_and_calculate.py:n tuotoksia
          git add Veikkaustilanne.md veikkausliiga_scraper.log \
                  data/cache/league_table_cache.json \
                  data/cache/player_stats_goals_cache.json \
                  data/cache/player_stats_assists_cache.json \
                  data/cache/*_raw.html || echo "Some veikkaus files not found, continuing."
          
          if git diff --staged --quiet; then
            echo "No changes to Veikkaustilanne.md or its related files."
          else
            COMMIT_TIME_UTC_VEIKKAUS=$(date -u +'%Y-%m-%d %H:%M:%S %Z')
            git commit -m "Automaattinen veikkausraportin päivitys ($COMMIT_TIME_UTC_VEIKKAUS)"
            # git pull --rebase || echo "Pull --rebase failed or not needed."
            sleep $((RANDOM % 5)) 
            git push || echo "Push for Veikkaustilanne.md failed, possibly due to concurrent updates."
          fi
