name: Update Match Data, Analyze, and Report

on:
  schedule:
    - cron: '20 */2 * * *' # Ajoitus hieman muutettu
  workflow_dispatch: 

jobs:
  scrape_analyze_report:
    runs-on: ubuntu-latest
    timeout-minutes: 30 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 selenium webdriver-manager requests pandas matplotlib seaborn plotly scikit-learn pathlib # Lisätty pathlib

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1 
        with:
          chrome-version: stable 

      - name: Run audience scraper
        id: scrape
        run: |
          echo "--- Running Python script: audience_scraper.py ---"
          python audience_scraper.py
          echo "--- Python script: audience_scraper.py finished ---"

      - name: Run data analysis and generate Markdown report
        id: analyze_and_report
        run: |
          echo "--- Running Python script: analyze_data.py (includes report generation) ---"
          python analyze_data.py 
          echo "--- Python script: analyze_data.py finished ---"
          # analyze_data.py tulostaa ::set-output name=md_file_path::PelatutOttelut.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MD_FILE_GENERATED_PATH: ${{ steps.analyze_and_report.outputs.md_file_path }}
        run: |
          echo "Markdown file path from analyze_data.py: '$MD_FILE_GENERATED_PATH'"
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Lisää tiedostot, joiden oletetaan muuttuvan tai syntyvän
          git add match_data.json last_match_id.txt match_scraper.log \
                  output/data/league_standings_calculated.csv || echo "Some primary data files not found, continuing."
          
          # Lisää Markdown-tiedosto, jos polku on saatu ja tiedosto on olemassa
          if [ -n "$MD_FILE_GENERATED_PATH" ] && [ -f "$MD_FILE_GENERATED_PATH" ]; then
            echo "Adding $MD_FILE_GENERATED_PATH to git."
            git add "$MD_FILE_GENERATED_PATH"
          else
            echo "Skipping git add for MD file: Path was '$MD_FILE_GENERATED_PATH' or file does not exist."
            # Yritä lisätä oletusnimellä, jos analyze_data.py ei asettanut outputtia mutta loi tiedoston
            if [ -f "PelatutOttelut.md" ]; then
              echo "Adding PelatutOttelut.md by default name."
              git add "PelatutOttelut.md"
            fi
          fi
          
          # Lisää scrape_cache-kansion sisältö
          if [ -d "scrape_cache" ]; then
            # Käytä findia turvallisemmin tiedostonimien kanssa, jotka voivat sisältää erikoismerkkejä
            find scrape_cache -type f \( -name '*.png' -o -name '*.html' \) -print0 | xargs -0 --no-run-if-empty git add || echo "No .png or .html files to add from scrape_cache or find/xargs command failed."
          else
            echo "scrape_cache directory does not exist, skipping adding files from it."
          fi
          
          # Tarkista muutokset
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            COMMIT_TIME_UTC=$(date -u +'%Y-%m-%d %H:%M:%S %Z')
            git commit -m "Päivitä otteludata, analyysit ja raportti ($COMMIT_TIME_UTC)"
            # Yritä ensin pull --rebase välttääksesi merge-konflikteja, jos remote on muuttunut
            # git pull --rebase || echo "Pull --rebase failed or not needed."
            sleep $((RANDOM % 5)) # Pieni satunnainen viive
            git push || echo "Push failed, possibly due to concurrent updates. Further investigation might be needed if this persists."
          fi
